In [31]:
import numpy as np
import pandas as pd 

In [64]:
X_test=np.loadtxt("C:\\Users\\Home\\Desktop\\boston dataset\\tanvi_test_boston_x_test.csv",delimiter=",")
X_test

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [65]:
train_data=np.loadtxt("C:\\Users\\Home\\Desktop\\boston dataset\\tanvi_training_boston_x_y_train.csv",delimiter=",")
train_data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [66]:
Y_train=train_data[:,13]
X_train = np.insert(data_train,13,1,axis = 1)
X_test = np.insert(X_test,13,1,axis = 1)
k = pd.DataFrame(X_train)
del k [14]
X_train = k.values
X_train.shape
tan=X_train.shape[1]
X_test.shape
X_train.shape


(379, 14)

In [67]:
def step_gradient(m,learning_rate,points):
    m_slope=np.zeros(14)
    M=len(points)
    for i in range(M):
        for j in range(tan):
            m_slope[j]+=(-2/M)*(Y_train[i]-(m*X_train[i]).sum())*X_train[i][j]
    m=m-learning_rate*m_slope
    return m

In [68]:
def gd(points,num_iterations,learning_rate):
    m=np.zeros(14) 
    for i in range(num_iterations):
        m=step_grad(m,learning_rate,points)
        print(i,'cost :',cost(m,points))
    return m

In [69]:
def run():
    num_iterations=200
    learning_rate=0.1
    m=gd(train_data,num_iterations,learning_rate)
    for i in range(tan):
        print(m[i])
    return m

In [70]:
def cost(m,points):
    total_cost=0
    M = len(points)
    for i in range(M):
        total_cost+=(1/M)*(Y_train[i]-(m*X_train[i]).sum())**2
    return total_cost

In [71]:
m=run()

0 cost : 374.24035597919686
1 cost : 245.37909656079904
2 cost : 165.10614192173668
3 cost : 114.49508621191686
4 cost : 82.43432664281796
5 cost : 62.041704688310936
6 cost : 49.0154746660482
7 cost : 40.65519326019772
8 cost : 35.25972835067592
9 cost : 31.754121492629718
10 cost : 29.457161634001743
11 cost : 27.936007022144533
12 cost : 26.914922412896374
13 cost : 26.217802951980175
14 cost : 25.731872822963105
15 cost : 25.38469911771804
16 cost : 25.129603525591076
17 cost : 24.936384410518777
18 cost : 24.785404792037365
19 cost : 24.66381822190748
20 cost : 24.56315514362143
21 cost : 24.477776518190055
22 cost : 24.403881200700226
23 cost : 24.338867434896198
24 cost : 24.280921148348455
25 cost : 24.228749732407817
26 cost : 24.18140930058519
27 cost : 24.138192120101166
28 cost : 24.09855285948923
29 cost : 24.06205993819115
30 cost : 24.028363158977218
31 cost : 23.997171942483217
32 cost : 23.968240497783352
33 cost : 23.941357557710433
34 cost : 23.916339140893513
35 cos

In [72]:
def predict(X_test,m):
    M=len(X_test)
    Y_pred=np.zeros(M)
    for i in range(M):
        Y_pred[i]=(m*X_test[i]).sum()
    print(Y_pred)
    return Y_pred


In [74]:
print(X_test.shape)
Y_pred=predict(X_test,m)
np.savetxt('bostonprediction.csv',Y_pred,fmt='%1.5f')
Y_pred

(127, 14)
[12.41880517 28.98353771 22.37914003 24.43714265 20.67757832  2.74754047
 30.32606577 24.84038423 18.6779513  23.53915222 24.11360859 17.73094142
 17.53358485 21.69136783 42.3394996  23.88824377 24.47373306 27.59094821
 20.27123636 31.20324726 23.86331327 24.99259743 33.94716364 36.41389133
 32.07271193 16.67825483 23.48686336 33.01368055 25.12766826 33.71238173
 16.90745076 26.07492375 23.28453438 25.46882545 15.00691239 29.60786851
 26.24814461 20.44060133 24.38837685  9.45174359  8.35241439 28.99424426
 29.61353958 19.78359519 20.35380156  3.12818036 39.51864515 25.71857338
 30.29336652 16.78390359 17.8733852  40.93811272 17.5619093  20.95178803
 15.61684999 21.37666995 18.45342083 23.1596074  13.69212628 17.21882006
 15.04528226 29.15264453 25.22737045 25.49634709 17.18745599 17.41837926
 34.69502674 17.00038936 27.06016624 22.52115378 29.31533087 27.09889678
 17.74237113  5.73136512 36.81062799 25.10198047 30.10337301 27.19874899
 16.24153273 32.67454581 19.25805294 22.7

array([12.41880517, 28.98353771, 22.37914003, 24.43714265, 20.67757832,
        2.74754047, 30.32606577, 24.84038423, 18.6779513 , 23.53915222,
       24.11360859, 17.73094142, 17.53358485, 21.69136783, 42.3394996 ,
       23.88824377, 24.47373306, 27.59094821, 20.27123636, 31.20324726,
       23.86331327, 24.99259743, 33.94716364, 36.41389133, 32.07271193,
       16.67825483, 23.48686336, 33.01368055, 25.12766826, 33.71238173,
       16.90745076, 26.07492375, 23.28453438, 25.46882545, 15.00691239,
       29.60786851, 26.24814461, 20.44060133, 24.38837685,  9.45174359,
        8.35241439, 28.99424426, 29.61353958, 19.78359519, 20.35380156,
        3.12818036, 39.51864515, 25.71857338, 30.29336652, 16.78390359,
       17.8733852 , 40.93811272, 17.5619093 , 20.95178803, 15.61684999,
       21.37666995, 18.45342083, 23.1596074 , 13.69212628, 17.21882006,
       15.04528226, 29.15264453, 25.22737045, 25.49634709, 17.18745599,
       17.41837926, 34.69502674, 17.00038936, 27.06016624, 22.52